# Generated by Django 4.1.2 on 2022-10-12 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_category_product_sub_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
