# Generated by Django 4.1.2 on 2022-10-14 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_product_sub_category_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additional_information',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_information', to='store.product'),
        ),
    ]
