# Generated by Django 4.1.2 on 2022-10-18 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_variation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
