# Generated by Django 4.1.2 on 2022-10-18 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_variation_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(blank=True, choices=[('color', 'color'), ('size', 'size')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='variation',
            name='variation_value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
