# Generated by Django 4.1.2 on 2022-10-18 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_variation_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Variation',
        ),
    ]
