# Generated by Django 4.1.2 on 2022-10-18 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_variation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Variation',
        ),
    ]
