# Generated by Django 4.1.2 on 2022-11-01 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_product_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additional_information',
            name='detail',
        ),
        migrations.AddField(
            model_name='additional_information',
            name='detail1',
            field=models.CharField(default='TEST', max_length=100),
        ),
        migrations.AddField(
            model_name='additional_information',
            name='detail2',
            field=models.CharField(default='TEST', max_length=100),
        ),
        migrations.AddField(
            model_name='additional_information',
            name='detail3',
            field=models.CharField(default='TEST', max_length=100),
        ),
    ]
