# Generated by Django 4.1.2 on 2022-11-05 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_remove_additional_information_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additional_information',
            name='detail1',
            field=models.CharField(blank=True, default='TEST', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='additional_information',
            name='detail2',
            field=models.CharField(blank=True, default='TEST', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='additional_information',
            name='detail3',
            field=models.CharField(blank=True, default='TEST', max_length=100, null=True),
        ),
    ]
