# Generated by Django 4.1.2 on 2022-11-09 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_rename_discount_product_discounted_price_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='category',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='product',
        ),
    ]
