# Generated by Django 4.1.2 on 2022-11-21 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_productgallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgallery',
            name='image1',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='store/products'),
        ),
        migrations.AddField(
            model_name='productgallery',
            name='image2',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='store/products'),
        ),
        migrations.AddField(
            model_name='productgallery',
            name='image3',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='store/products'),
        ),
    ]
