# Generated by Django 4.1.2 on 2022-11-21 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_productgallery_image1_productgallery_image2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productgallery',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='productgallery',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='productgallery',
            name='image3',
        ),
    ]
