# Generated by Django 4.1.2 on 2022-10-12 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_sub_category_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub_category',
            name='category',
        ),
    ]
