# Generated by Django 4.1.2 on 2022-10-17 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_additional_information_product'),
        ('cart', '0004_alter_cartitem_cart_alter_cartitem_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_item', to='store.product'),
        ),
    ]
