# Generated by Django 4.1.2 on 2022-11-08 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='user',
        ),
    ]
