# Generated by Django 4.1.2 on 2022-11-09 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_remove_orderproduct_variations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='status',
            field=models.CharField(choices=[('Placed', 'Placed'), ('Accepted', 'Accepted'), ('Shiped', 'Shiped'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered'), ('Return Initiated', 'Return Initiated'), ('Returned', 'Returned'), ('Cancelled', 'Cancelled')], default='Placed', max_length=20),
        ),
    ]
